version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wallet_test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d wallet_test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  wallet-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      DB_HOST: postgres-test
      DB_PORT: 5432
      DB_USER: test_user
      DB_PASSWORD: test_password
      DB_NAME: wallet_test_db
      GIN_MODE: test
    depends_on:
      postgres-test:
        condition: service_healthy
    volumes:
      - .:/app
    command: ["go", "test", "-v", "./...", "-tags=integration"]

volumes:
  postgres_test_data:
